### ISSUE TITLE
maintaince status

### ISSUE THREAD

**Issue by vtolstov** [vtorri/etui#11]
Thanks for this project, but i see that latest commit long time ago, does it compile with latest efl ?

**Comment by vtorri** [comment]
it will compile with the latest efl (more precisely : efl 1.19)

**Comment by vtorri** [comment]
It compiles currently with the git tree

**Comment by vtorri** [comment]
no problem on openbsd, fedora, windows, small problem with embedded jpeg in a pdf with arch (specific to arch) with current git

anyway efl 1.20 will be required so closing
