### ISSUE TITLE
pdf module is not correctly loaded on UNIX

### ISSUE THREAD

**Issue by vtorri** [vtorri/etui#14]
it seems that on Linux (arch) and OpenBSD, the pdf module is not loaded

**Comment by vtorri** [comment]
it works on arch and openbsd, it seems

but okra has problems with fedora (while i don't on the fedora in virtualbox)

**Comment by wltjr** [comment]
These issue maybe similar to that I experienced on Gentoo. Maybe has to do with how it was built.

**Comment by vtorri** [comment]
is it still the case ?

**Comment by wltjr** [comment]
This can likely be closed now. I believe all issues regarding this have been resolved.

**Comment by vtorri** [comment]
no problem on fedora, openbsd and arch
open a ticket if needed
