### ISSUE TITLE
Build failure on Arch with latest stable E.

### ISSUE THREAD

**Issue by ApostolosB** [vtorri/etui#2]
Tried to build it on Arch with latest stable E stack and fails as below:

 src/modules/ps/ps.c:2241:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&doseps->checksum,    2, 1, FD_FILE);
     ^
  CC       src/modules/ps/src_modules_ps_module_la-etui_module_ps.lo
src/modules/ps/etui_module_ps.c: In function ‘_etui_ps_gs_process’:
src/modules/ps/etui_module_ps.c:279:23: error: ‘e_NeedInput’ undeclared (first use in this function)
         err = (err == e_NeedInput) ? 0 : err;
                       ^
src/modules/ps/etui_module_ps.c:279:23: note: each undeclared identifier is reported only once for each function it appears in
Makefile:5247: recipe for target 'src/modules/ps/src_modules_ps_module_la-etui_module_ps.lo' failed
make[1]: **\* [src/modules/ps/src_modules_ps_module_la-etui_module_ps.lo] Error 1
make[1]: Leaving directory '/home/toliz/Desktop/etui-git/src/etui'
Makefile:1833: recipe for target 'all' failed
make: **\* [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by vtorri** [comment]
It's a change in ghostscript 9.18 : http://bugs.ghostscript.com/show_bug.cgi?id=696317

**Comment by ApostolosB** [comment]
Yeah if you change e_NeedInput to gs_error_NeedInput compiles. 

BTW are you still maintaining this app or its left to die? I am asking cause there are more issues with it.

**Comment by vtorri** [comment]
actually, i want to replace ghostscript by a new lib, named xpost, which is not AGPL (which I don't like). I'm also working on libdvi, to display DVI files. So I have little time for etui, but you're right, letting etui in such state is not good. I will try to fix this. If you want to provide a patch, please feel free to add it.

**Comment by ApostolosB** [comment]
Pull request submitted. 

There are other issues with etui. Ie. problems with keybindings, no desktop icon appears etc. I will file separate bug reports.

E needs a proper .pdf reader :smile_cat:

**Comment by vtorri** [comment]
I tried to fix this for both ghostscrip >=9.18 and < 9.18. Can you pull and try again, please ?

**Comment by ApostolosB** [comment]
Compiles thanks.

Closing this.
