### ISSUE TITLE
File chooser freezes the interface.

### ISSUE THREAD

**Issue by ApostolosB** [vtorri/etui#20]
...either when you rclick and choose open or when you launch etui from the menu.

You see something like > https://www.enlightenment.org/ss/display.php?image=e-591c49ea85cb93.34096862.png and you have to kill it. It also uses 100%CPU.

**Comment by vtorri** [comment]
I'm writing my own file chooser. I've looked at the code of elm_fileselector and I even don't know where to start to debug it...

**Comment by wltjr** [comment]
I think this may be resolved. I had this issue at first, but I am not experiencing it anymore. I also use the same elm_fileselector in ecrire. Even when it used 100% for etui, it did not for ecrire. It seemed to be some odd bug. I would check to see if it still exists.

**Comment by vtorri** [comment]
Fixed in 0a1a36ce8264413485cd62398398b8ef5337d138
