### ISSUE TITLE
Feature request - Ability to fill out PDF forms

### ISSUE THREAD

**Issue by wltjr** [vtorri/etui#31]
This maybe a limitation of mupdf, not sure. But it would be great to have the ability to fill out a PDF form, and save or print that. I think printing support is another feature request for down the road. EFL or E likely needs a print dialog and such. Presently have the need for such and situation on editable PDFs on Linux is not that great. Few free online ones, and not sure about the paying ones onilne. Acrobat stopped long ago and is only 32bit. A hole not really filled on Linux/Unix easily.

This is a long term request, no expectations. Just something that would be nice to have someday.

**Comment by vtorri** [comment]
mupdf allows filling forms and it is a must-do. I will code it once i finish the search.
saving is something that i should do (mudraw can do that)
about edition of PDF (if possible), is also something i want to do but it is a long term code

**Comment by wltjr** [comment]
The mupdf UI does not seem to support forms. That is great it has such abilities that can be utilized. Just strange they did not put it to use in their own UI. No worries.

**Comment by wltjr** [comment]
This is a duplicate of #22
