### ISSUE TITLE
Doesn't compile against efl 1.23.0

### ISSUE THREAD

**Issue by NuLogicSystems** [vtorri/etui#37]
As the title suggests, I can't get it to compile.
Currently using meson/ninja, but had issues using autotools/gcc make as well.
Here is my current PKGBUILD: https://sourceforge.net/p/nulogicos/PKGBUILD/ci/master/tree/etui/PKGBUILD

and the output from makepkg: https://pastebin.com/3d6wSXmn

**Comment by vtorri** [comment]
ok, there is a missing -pthread on unix. I'll fix that, thanks

(the warning about strdup is strange as string.h is included, i have this on Windows too)

**Comment by vtorri** [comment]
do you have -pthread or -lpthread in your eina.pc ?

**Comment by NuLogicSystems** [comment]
Where would I look for that?

**Comment by vtorri** [comment]
it's in $prefix/lib/pkgconfig where prefix is where you install etui

usually, /usr/lib/pkgconfig or /usr/local/lib/pkgconfig

you may replace lib with lib64 if you don't find eina.pc

**Comment by NuLogicSystems** [comment]
`prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: eina
Description: efl: eina
Version: 1.23.0
Requires.private: libsystemd, libunwind-generic
Libs: -pthread -L${libdir} -leina
Libs.private: -lm -lrt -ldl
Cflags: -I${includedir}/eina-1 -I${includedir}/efl-1 -I${includedir}/eina-1/eina -pthread
`

So yes.

**Comment by vtorri** [comment]
if you replace -pthread with -lpthread (in Libs and Cflags), does it work ? notethat you should clean etui first (ninja clean)

**Comment by NuLogicSystems** [comment]
Nope, same things..

**Comment by vtorri** [comment]
normally you have launched meson in a subdir ($srcdir/$_pkgname according to your PKGBUILD)

in it you will find a build.ninja file. can you send it to me please ?

**Comment by NuLogicSystems** [comment]
I'll send it both ways. default and -lpthread.

**Comment by NuLogicSystems** [comment]
[meson-lpthread.zip](https://github.com/vtorri/etui/files/3704504/meson-lpthread.zip)

**Comment by NuLogicSystems** [comment]
[meson-pthread.zip](https://github.com/vtorri/etui/files/3704517/meson-pthread.zip)

**Comment by vtorri** [comment]
i don't want meson.build, i want build.ninja

**Comment by NuLogicSystems** [comment]
OK, no such beast in that directory...
![Screenshot_20191008_181533](https://user-images.githubusercontent.com/10186587/66437412-a838cf00-e9f7-11e9-96bc-589d9088ceaf.png)

**Comment by NuLogicSystems** [comment]
Unless you meant the one in the build directory.

[build.ninja.zip](https://github.com/vtorri/etui/files/3704740/build.ninja.zip)

**Comment by vtorri** [comment]
problem is, imho, in eina.pc, see https://phab.enlightenment.org/T8310

**Comment by NuLogicSystems** [comment]
Once again, with -pthrerad, or -lpthreads, in eina.pc makes no difference, it still does not compile, throwing out same exact errors.

**Comment by vtorri** [comment]
pthread_rwlock_t is not available, one must set a macro to make it "visible".
try this : 

export CPPFLAGS=-D_POSIX_C_SOURCE=200809L
relaunch meson
then ninja

**Comment by NuLogicSystems** [comment]
I compile efl with internal api's hidden as suggested by raster:
CFLAGS="$CFLAGS -fvisibility=hidden"
CXXFLAGS="$CXXFLAGS -fvisibility=hidden"

**Comment by NuLogicSystems** [comment]
So I added that export and now we have a different error.
https://pastebin.com/DUtc8cce

On a side note, what's up with this:
Dependency libarchive found: NO found '3.4.0' but need: ' >= 3'

**Comment by vtorri** [comment]
Please check again, it works here on fedora. I've also fixed the detection of libarchive

**Comment by NuLogicSystems** [comment]
And we have a winner.
Compiles with some warnings, but it does compile.
and now with comic book as well, aka libarchive detecting fine.
Now lets see if it works.

**Comment by NuLogicSystems** [comment]
OK, it compiles now but doesn't open any of my pdf files.

**Comment by vtorri** [comment]
do you have this kind of error in terminal : eina_module_load() : could not dlopen() ...../pdf/../libmodule.so : undefined symbol *****

i have this error on fedora, with missing jbig2dec

**Comment by vtorri** [comment]
https://www.mail-archive.com/debian-printing@lists.debian.org/msg10745.html

**Comment by NuLogicSystems** [comment]
![Screenshot_20191011_163529](https://user-images.githubusercontent.com/10186587/66683376-4b325880-ec45-11e9-942d-b4a4440db9a5.png)

That sucks :(

**Comment by vtorri** [comment]
i've installed it, but i still have an undefined symbol error message in the terminal. It seems that the version of jbig2dec 0.16 is not good and 0.17 is needed
can you show me a screen shot of what is in your terminal

if mupdf is too problematic, i'll try with pdfium

**Comment by NuLogicSystems** [comment]
![Screenshot_20191011_164342](https://user-images.githubusercontent.com/10186587/66683797-55088b80-ec46-11e9-8d05-5886056bb2d3.png)

You hit the nail on the head, dolphin also doesn't show thumbnails of pdf's anymore.

**Comment by vtorri** [comment]
same for me : do you see the truncated first line . It finishes with : undefined symbol jbig2_ctx_new

that is the problem (see link about the mail above). I'll ask mupdf guys, as they write also jbig2dec

**Comment by NuLogicSystems** [comment]
Any news on this issue?

**Comment by vtorri** [comment]
well, you can downgrade jbig2dec, or see if archlinux has updated jbig2dec to 0.17

see https://github.com/ArtifexSoftware/jbig2dec/releases

**Comment by NuLogicSystems** [comment]
Yes, 0.17 is indeed updated since 2 days ago in upstream in arch.
I'll just need to wait for it to come downstream to Manjaro.

**Comment by vtorri** [comment]
once it's in manjaro, tell me if it works or not

thank you

**Comment by vtorri** [comment]
is it ok now ?

**Comment by ApostolosB** [comment]
This seems to work ok. Compiled it on latest stable just fine.
