### ISSUE TITLE
doesn't compile with mupdf-1.17.0

### ISSUE THREAD

**Issue by Millak** [vtorri/etui#40]
[10/26] Compiling C object 'src/modules/pdf/bb1e916@@module@sha/etui_module_pdf.c.o'.
FAILED: src/modules/pdf/bb1e916@@module@sha/etui_module_pdf.c.o gcc -Isrc/modules/pdf/bb1e916@@module@sha -Isrc/modules/pdf -I../source/src/modules/pdf -I. -I../source/ -I/gnu/stor/3k4w51sf5pprpdchqqq6ssgfx51qqn8a-my-mupdf-1.17.0/include -Isrc/lib -I../source/src/lib -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eina-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/efl-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eina-1/eina -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/ecore-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/efl-1/interfaces -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eo-1 -I/gnu/store/rmbxm1fg47b347kv1h5fb2w04nxqbsj6-glib-2.62.6/include/glib-2.0 -I/gnu/store/rmbxm1fg47b347kv1h5fb2w04nxqbsj6-glib-2.62.6/lib/glib-2.0/include -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/evas-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/evas-1/canvas -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/evas-1/gesture -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/ector-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eet-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/emile-1 -I/gnu/store/n4xx7mrgk4xgy8kczpbn0z1jvnq504rh-luajit-2.1.0-beta3/include/luajit-2.1 -I/gnu/store/3x2kak8abb6z2klch72kfff2qxzv00pj-libpng-1.6.37/include/libpng16 -I/gnu/store/3jzvmv2an5aw4m0mpg949knrm8r3nwxy-harfbuzz-2.6.4/include/harfbuzz -I/gnu/store/llccvnpm1dm94d7lndrhs2m6421p45pd-fribidi-1.0.9/include/fribidi -I/gnu/store/haaam6v8l4s75mj9xmpb9gc78xk001y9-freetype-2.10.1/include/freetype2 -I/gnu/store/a45p39mgqvfd8kjwibyr0q42k1mw7gmf-util-linux-2.35.1-lib/include/uuid -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eio-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/efreet-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/
ecore-file-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/ecore-ipc-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/ecore-con-1 -I/gnu/store/n74bjzcw8yz3mhq2ip3l144hck2l6y5r-efl-1.24.2/include/eldbus-1 -I/gnu/store/9xbmwzl08wpkdjvya4x55hksi134255l-dbus-1.12.16/include/dbus-1.0 -I/gnu/store/9xbmwzl08wpkdjvya4x55hksi134255l-dbus-1.12.16/lib/dbus-1.0/include -I/gnu/store/16wvggwwxyq3s8i85596nj4a29j4nv1z-openjpeg-2.3.1/include/openjpeg-2.3 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -Wall -Wextra -Wshadow -Wstrict-prototypes -Werror=missing-prototypes -Werror=pointer-arith -Wno-missing-field-initializers -fvisibility=hidden -fPIC -pthread -DHAVE_CONFIG_H -DDLL_EXPORT -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=500 -DECRIN_ETUI_BUILD -MD -MQ 'src/modules/pdf/bb1e916@@module@sha/etui_module_pdf.c.o' -MF 'src/modules/pdf/bb1e916@@module@sha/etui_module_pdf.c.o.d' -o 'src/modules/pdf/bb1e916@@module@sha/etui_module_pdf.c.o' -c ../source/src/modules/pdf/etui_module_pdf.c
../source/src/modules/pdf/etui_module_pdf.c: In function ‘_etui_pdf_toc_fill’:
../source/src/modules/pdf/etui_module_pdf.c:277:20: error: incompatible types when assigning to type ‘int’ from type ‘fz_location {aka struct <anonymous>}’
             l.page = fz_resolve_link(md->doc.ctx, md->doc.doc,
                    ^
../source/src/modules/pdf/etui_module_pdf.c: In function ‘_etui_pdf_page_set’:
../source/src/modules/pdf/etui_module_pdf.c:650:14: warning: unused variable ‘links’ [-Wunused-variable]
     fz_link *links;
              ^~~~~
../source/src/modules/pdf/etui_module_pdf.c: In function ‘_etui_pdf_page_size_get’:
../source/src/modules/pdf/etui_module_pdf.c:723:13: warning: unused variable ‘rect’ [-Wunused-variable]
     fz_rect rect;
             ^~~~
[11/26] Linking target src/modules/djvu/libmodule.so.
ninja: build stopped: subcommand failed.
command "ninja" "-j" "2" failed with status 1

**Comment by vtorri** [comment]
which mupdf version are you using, please ? I fear another API break

**Comment by vtorri** [comment]
forget it, you mentioned it's mupdf 1.17 :-)

**Comment by vtorri** [comment]
i'll fix it, thanks

**Comment by vtorri** [comment]
fixed in 2a3b8c85d2ac5ed345a6c36c8c66f4772cc5e80c
