### ISSUE TITLE
Doubleclicking on a pdf to open doesn't work.

### ISSUE THREAD

**Issue by ApostolosB** [vtorri/etui#6]
Have a .pdf on the desktop.
Double click to open it. 
Etui starts and shows the window with the icon without displaying the .pdf.

If you start it from the command line with etui /path/to/file it works.

**Comment by vtorri** [comment]
do you have an idea of the problem ? it seems to be a problem of the environment, not etui, i think (the way the desktop launches programs with arguments)

**Comment by ApostolosB** [comment]
No idea TBH. Other stuff like photos open by doubelclick. The only difference i see when starting it from the command like (which works) to doubleclicking (which doesn't) is on the top bar of the window.

Command line reads > etui -  Desktop/File.pdf

Doubleclick reads > etui - file:///home/name/Desktop/File.pdf

**Comment by vtorri** [comment]
ho, i do not manage URI, then, I think

**Comment by vtorri** [comment]
Can you try that patch: 
[etui_uri.diff.gz](https://github.com/vtorri/etui/files/252943/etui_uri.diff.gz)
i can't test right now

**Comment by ApostolosB** [comment]
With this patch doubleclicking on a file works.

**Comment by vtorri** [comment]
pushed, thanks
