### ISSUE TITLE
Center the document to the window.

### ISSUE THREAD

**Issue by ApostolosB** [vtorri/etui#8]
The alignment of the document you view is to the left. When you fullscreen the window -or resizing it to be bigger than the document- the document stays on the left. 

An aesthetics issue.

**Comment by vtorri** [comment]
i've reimplemented the fullscreen code (after fixing the win32 code of fullscreen in the EFL first). There is still this error

i'll investigate more as now i'm more satisfied with the UI

**Comment by vtorri** [comment]
fixed in git
